export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Premium Banking',
    headline: 'Unlimited Transactions with zero fees',
    description: 'Get access to our app exclusive to members that allows to send money anytime, anywhere, with no fees.',
    buttonLabel: 'Get Started',
    imgStart: false,
    img: require('../../images/svg-1.svg'),
    alt: 'mobile phone',
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjTwo = {
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Credit',
    headline: 'Earn more with our 5% Cashback Rewards Card',
    buttonLabel: 'Learn More',
    imgStart: true,
    img: require('../../images/svg-2.svg'),
    alt: 'mobile phone',
    dark: false,
    primary: false,
    darkText: true,
}

export const homeObjThree = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Personal Finance',
    headline: 'Take control of your spending',
    description: 'Use our built-in spending tracker to see where your money is going every month.',
    buttonLabel: 'Become a Member',
    imgStart: false,
    img: require('../../images/svg-4.svg'),
    alt: 'mobile phone',
    dark: true,
    primary: true,
    darkText: false,
};